<?php

/**
 * Class ZohoAuth класс с единственным методом генерации токена
 */
class ZohoAuth
{

    /**
     * генерация AuthToken доступа в ZohoCRM
     *
     */
    public static function GenerateAuthToken()
    {
        $userdatajson = file_get_contents('UserData.json');
        $userdatadec = json_decode($userdatajson, true);
        $email = $userdatadec['Email'];
        $password = $userdatadec['Password'];
        $appname = $userdatadec['AppName'];
        if ((empty($password) || empty($email)) || empty($appname)) {
            return "One of user data parameter in UserData.json is empty please check file";
        } else {
            $url = "https://accounts.zoho.com/apiauthtoken/nb/create?SCOPE=ZohoCRM/crmapi&EMAIL_ID=" . $email . "&PASSWORD=" . $password . "&DISPLAY_NAME=" . $appname;
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_TIMEOUT, 30);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
            $result = curl_exec($ch);
            curl_close($ch);;
            if (substr_count($result, 'FALSE') > 0) {
                file_put_contents(dirname(__FILE__) .'/ErrorsLog.txt', date('Y-m-d H:i:s') . "Error: " . $result . "\n", FILE_APPEND);
                return "Your user data parameter in UserData.php has wrong value";
            } else {
                $fptoken = fopen(dirname(__FILE__) . '/AuthTokenInfo.txt', "w");
                fwrite($fptoken, $result);
                fclose($fptoken);
                return "Authtoken generated";
            }
        }
    }

    /**
     * получения AuthToken доступа в ZohoCRM из файла после генерации
     *
     */
    public static function GetAuthToken()
    {
        $authinfo = file_get_contents(dirname(__FILE__) .'/AuthTokenInfo.txt');
        if (empty($authinfo)){
            file_put_contents(dirname(__FILE__) .'/ErrorsLog.txt', date('Y-m-d H:i:s') . "Error: AuthToken do not generated by ZohoAuth::GenerateAuthToken method please generate it again \n", FILE_APPEND);
            return null;
        } else {
            $start = strrpos($authinfo,'KEN=');
            $end = strrpos($authinfo,'RES');
            $result = substr($authinfo,$start+4,$end-$start-5);
            return $result;
        }
    }
}